layout: "layout/3d.yaml"

tech:
  chiplet: "tech/chiplet.yaml"
  interposer: "tech/interposer_org.yaml"

network:
  noi: "network/meshnoi.yaml"
  nol: "network/nol.yaml"
  noc: "network/noc.yaml"
  params: "network/network_3d.yaml"

system: "system/system_3d.yaml"
placement: "placement/place_model_3d.yaml"

simulation:
  traffic: shuffle
  injection_rate: 0.1
  sim_cycles: 500000
  bonding: ubump10
  c2c_bonding: ubump10
